### PR TITLE
Rider 2021.2.1

### PR DESCRIPTION
**Pull request by Snegovikufa**

### CODE REVIEW

**Comment by afelinczak** [comment]
Hello @Snegovikufa,
Do you think you can provide binary build on your fork ? 
I'm not sure when @vladyslav-burylov will accept PR and provide update to the plugin.

**Comment by Snegovikufa** [comment]
Hello @afelinczak,
I have added release binaries in my fork

**Comment by afelinczak** [comment]
@Snegovikufa Thank you so much, can confirm it works in latest Rider.

**Comment by vladyslav-burylov** [comment]
Hi guys, I recently moved to different country, thus I’m was little bit busy with personal stuff. However I will take a look on a weekend. Thanks for creating PR!

**Comment by vladyslav-burylov** [comment]
@Snegovikufa - thank you for creating PR and doing some cleanup, really appreciate it!

**Comment by vladyslav-burylov** [comment]
p.s. I am sorry for delay, guys

**Pull request merged**
